/* 
Написать процедуру, которая за указанный период определяет 
для указанного вида техники количество предоставлений и
перечень произведённых работ. В качестве параметра передать
идентификатор техники, начальную и конечную дату периода. 
Пример: id = 94, период: с '04-APR-18' до '04-APR-20'
*/

CREATE OR REPLACE PROCEDURE 
PROVISION_FOR_PERIOD(FROM_DATE IN DATE, TO_DATE IN DATE, TECH_ID IN INTEGER) IS
CURSOR WORKS_LIST IS 
SELECT W.wname
FROM Technics T
INNER JOIN Provision P ON T.snumber = P.snumber
INNER JOIN Works W ON P.wcode = W.wcode
WHERE T.snumber = TECH_ID
AND P.rdate BETWEEN FROM_DATE AND TO_DATE;
INVALID_ID_EXCEPTION EXCEPTION;
INVALID_DATE_EXCEPTION EXCEPTION;
NO_DATA_FOUND_EXCEPTION EXCEPTION;
-- EXCEPTIONS: FROM > TO, NO DATA FOUND;
COUNTER INTEGER := 0;
BEGIN
	IF TECH_ID <= 0 THEN 
		RAISE INVALID_ID_EXCEPTION;
	END IF;
    
    IF FROM_DATE > TO_DATE THEN
		RAISE INVALID_DATE_EXCEPTION
	END IF;
    
	FOR WORK_NAME IN WORKS_LIST
    LOOP
		DBMS_OUTPUT.PUT_LINE('WORK NAME: ' || WORK_NAME.wname);
        COUNTER := COUNTER + 1;
    END LOOP;
    
    IF COUNTER > 0 THEN
		DBMS_OUTPUT.PUT_LINE('NUMBER OF PROVISIONS: ' || COUNTER);
	ELSE 
		RAISE NO_DATA_FOUND_EXCEPTION;
	END IF;
    
    EXCEPTION
		WHEN INVALID_ID_EXCEPTION THEN 
			DBMS_OUTPUT.PUT_LINE('ID MUST BE POSITIVE');
        WHEN INVALID_DATE_EXCEPTION THEN 
			DBMS_OUTPUT.PUT_LINE('FROM_DATE CANNOT BE GREATER THAN TO_DATE');
		WHEN NO_DATA_FOUND_EXCEPTION THEN 
			DBMS_OUTPUT.PUT_LINE('REQURIED DATA DOESNT EXIST');
        WHEN OTHERS 
			DBMS_OUTPUT.PUT_LINE('IF YOU READING THAT YOU MADE A FATAL MISTAKE');
END;
/